{ pkgs
, inputs
, lib
, config
, ...
}:
let
  inherit (inputs) nixgl;
in
{
  imports = [
    ../../modules/shared/programs/git.nix
    ../../modules/shared/programs/zsh.nix
    ../../modules/shared/programs/direnv.nix
    ../../modules/shared/programs/alacritty.nix
  ];

  nixGL = {
    inherit (nixgl) packages;
    defaultWrapper = "nvidiaPrime";
    offloadWrapper = "mesa";
    installScripts = [ "mesa" "nvidiaPrime" ];
  };

  home = {
    username = config.sharedVariables.user;
    homeDirectory = config.sharedVariables.homeDir;
    packages = with pkgs; [
      keepassxc
      firefox
      thunderbird
      rofi
      polybar

      # development
      uv
      ripgrep
      docker
      tree
      inputs.nixvim.packages.${pkgs.system}.default
      (config.lib.nixGL.wrap inputs.ghostty.packages.${pkgs.system}.default)

      #fonts
      meslo-lgs-nf
      font-awesome
      noto-fonts
      noto-fonts-emoji
    ];
    file = {
      ".config/i3/config".source = ../../modules/dotfiles/linux/i3/config;
      ".config/ghostty/config".text = ''
        # Config generated by Ghostty Config

        shell-integration = zsh
        theme = catppuccin-mocha
        clipboard-read = allow
        clipboard-write = allow
        window-theme = dark
        gtk-titlebar = false
      '';
    };
  };

  nixpkgs.config.allowUnfree = true;
  fonts.fontconfig.enable = true;

  programs = {
    home-manager.enable = true;
    alacritty.package = config.lib.nixGL.wrap pkgs.alacritty;
  };

  home.stateVersion = "24.11";
}
