name: Build NixOS AArch64 ISO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-aarch64-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          extra_nix_config: |
            build-max-derivations = 500

      - name: Build NixOS AArch64 ISO
        run: |
          nix build .#nixosConfigurations.iso.config.system.build.isoImage

      - name: Upload AArch64 ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-aarch64-iso
          path: result/*.iso
          retention-days: 7
