name: Flake Check

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
      - "apps/**"
  workflow_dispatch: # Allows manual trigger

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Run Nix flake checks
        run: nix flake check
