name: Run flake check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Run flake check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v10 # This action
